octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development
    - staging
    - production
  development:
    ohio_ro:
      adapter: mysql2
#      host: host.docker.internal
      host: unicorn-ads.cluster-ro-cy9qnb8dhqgs.us-east-2.rds.amazonaws.com
      database: ads
      username: ads
      password: Hacker355!
      port: 3306
    frankfurt_ro:
      adapter: mysql2
#      host: host.docker.internal
      host: unicorn-ads.cluster-ro-cy9qnb8dhqgs.us-east-2.rds.amazonaws.com
      database: ads
      username: ads
      password: Hacker355!
      port: 3306
  staging:
    read_replica:
      adapter: mysql2
      host: <%= ENV['RDS_READ_REPLICA_HOSTNAME'] %>
      database: ads
      username: ads
      password: Hacker355!
      reconnect: true
  production:
    read_replica:
      adapter: mysql2
      host: <%= ENV['RDS_READ_REPLICA_HOSTNAME'] %>
      database: <%= ENV['ADS_DB_NAME'] %>
      username: <%= ENV['ADS_DB_USERNAME'] %>
      password: <%= ENV['ADS_DB_PASSWORD'] %>
      reconnect: true
    x_region_read_replica:
      adapter: mysql2
      host: <%= ENV['RDS_READ_REPLICA_HOSTNAME'] %>
      database: <%= ENV['ADS_DB_NAME'] %>
      username: <%= ENV['ADS_DB_USERNAME'] %>
      password: <%= ENV['ADS_DB_PASSWORD'] %>
      reconnect: true
