octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development
    - staging
    - production
  development:
    ohio_ro:
      adapter: mysql2
      host: [YOUR_DB_CLUSTER_READONLY_ENDPOINT_IN_PRIMARY_REGION]
      database: ads
      username: ads
      password: [DB_PASSWORD]
      port: 3306
      reconnect: true
    frankfurt:
      adapter: mysql2
      host: [YOUR_DB_CLUSTER_ENDPOINT_IN_SECONDARY_REGION]
      database: ads
      username: ads
      password: [DB_PASSWORD]
      port: 3306
      reconnect: true
    frankfurt_ro:
      adapter: mysql2
      host: [YOUR_DB_CLUSTER_READONLY_ENDPOINT_IN_SECONDARY_REGION]
      database: ads
      username: ads
      password: [DB_PASSWORD]
      port: 3306
      reconnect: true
  staging:
    read_replica:
      adapter: mysql2
      host: <%= ENV['RDS_READ_REPLICA_HOSTNAME'] %>
      database: ads
      username: ads
      password: [DB_PASSWORD]
      reconnect: true
  production:
    ohio_ro:
      adapter: mysql2
      host: <%= ENV['ADS_DB_HOST_OHIO_RO'] %>
      database: <%= ENV['ADS_DB_NAME'] %>
      username: <%= ENV['ADS_DB_USERNAME'] %>
      password: <%= ENV['ADS_DB_PASSWORD'] %>
      port: 3306
      reconnect: true
    frankfurt:
      adapter: mysql2
      host: <%= ENV['ADS_DB_HOST_FRANKFURT'] %>
      database: <%= ENV['ADS_DB_NAME'] %>
      username: <%= ENV['ADS_DB_USERNAME'] %>
      password: <%= ENV['ADS_DB_PASSWORD'] %>
      port: 3306
      reconnect: true
    frankfurt_ro:
      adapter: mysql2
      host: <%= ENV['ADS_DB_HOST_FRANKFURT_RO'] %>
      database: <%= ENV['ADS_DB_NAME'] %>
      username: <%= ENV['ADS_DB_USERNAME'] %>
      password: <%= ENV['ADS_DB_PASSWORD'] %>
      port: 3306
      reconnect: true
